name: Embedded Builds

on: push
jobs:
  llvm_clang:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        env:
        - TYPE: Debug
          NAME: debian_llvm+libclang+glibc2.27
          LLVM_VERSION: 8
          STATIC_LINKING: ON
          STATIC_LIBC: OFF
          EMBED_LLVM: OFF
          EMBED_CLANG: ON
          EMBED_LIBCLANG_ONLY: ON
          EMBED_BCC: OFF
          EMBED_LIBELF: OFF
          EMBED_BINUTILS: OFF
          RUN_ALL_TESTS: 1
          RUNTIME_TEST_DISABLE: builtin.cgroup,probe.kprobe_offset_fail_size
          DISTRO: bionic
        - TYPE: Release
          NAME: debian_llvm+libclang+glibc2.27
          LLVM_VERSION: 8
          STATIC_LINKING: ON
          STATIC_LIBC: OFF
          EMBED_LLVM: OFF
          EMBED_CLANG: ON
          EMBED_LIBCLANG_ONLY: ON
          EMBED_BCC: OFF
          EMBED_LIBELF: OFF
          EMBED_BINUTILS: OFF
          RUN_ALL_TESTS: 1
          RUNTIME_TEST_DISABLE: builtin.cgroup,probe.kprobe_offset_fail_size
          DISTRO: bionic
        - TYPE: Release
          NAME: vanilla_llvm+clang+glibc2.27
          LLVM_VERSION: 8
          STATIC_LINKING: ON
          STATIC_LIBC: OFF
          EMBED_LLVM: ON
          EMBED_CLANG: ON
          EMBED_LIBCLANG_ONLY: OFF
          EMBED_BCC: OFF
          EMBED_LIBELF: OFF
          EMBED_BINUTILS: OFF
          RUN_ALL_TESTS: 1
          RUNTIME_TEST_DISABLE: builtin.cgroup,probe.kprobe_offset_fail_size
          DISTRO: bionic
        - TYPE: Release
          NAME: vanilla_llvm+clang+glibc2.23
          LLVM_VERSION: 8
          STATIC_LINKING: ON
          STATIC_LIBC: OFF
          EMBED_LLVM: ON
          EMBED_CLANG: ON
          EMBED_LIBCLANG_ONLY: OFF
          EMBED_BCC: OFF
          EMBED_LIBELF: OFF
          EMBED_BINUTILS: OFF
          RUN_ALL_TESTS: 1
          RUNTIME_TEST_DISABLE: builtin.cgroup,probe.kprobe_offset_fail_size,other.string compare map lookup
          DISTRO: xenial
          CMAKE_EXTRA_FLAGS: "-DCMAKE_CXX_FLAGS='-include /usr/local/include/bcc/compat/linux/bpf.h -D__LINUX_BPF_H__'"
    steps:
    - uses: actions/checkout@v2
    - name: Build docker container
      run: |
        docker build -t bpftrace-embedded-${{ matrix.env['DISTRO'] }} -f docker/Dockerfile.ubuntu-glibc --build-arg bcc_ref=${{ matrix.env['BCC_REF'] }} --build-arg DISTRO=${{ matrix.env['DISTRO'] }}  docker/
    - name: bpftrace embedded build
      env: ${{ matrix.env }}
      run: |
        docker run --privileged -v $(pwd):$(pwd) -w $(pwd) -v /sys/kernel/debug:/sys/kernel/debug:rw -v /lib/modules:/lib/modules:ro -v /usr/src:/usr/src:ro -e STATIC_LINKING=${STATIC_LINKING} -e STATIC_LIBC=${STATIC_LIBC} -e EMBED_LLVM=${EMBED_LLVM} -e EMBED_CLANG=${EMBED_CLANG} -e EMBED_BCC=${EMBED_BCC} -e EMBED_LIBELF=${EMBED_LIBELF} -e EMBED_LIBCLANG_ONLY=${EMBED_LIBCLANG_ONLY} -e EMBED_BINUTILS=${EMBED_BINUTILS} -e RUN_ALL_TESTS=${RUN_ALL_TESTS} -e CMAKE_EXTRA_FLAGS="${CMAKE_EXTRA_FLAGS}" -e RUNTIME_TEST_DISABLE="${RUNTIME_TEST_DISABLE}" bpftrace-embedded-${{ matrix.env['DISTRO'] }} $(pwd)/build-embedded ${TYPE} -j`nproc`
    - name: Check linked libs
      env: ${{ matrix.env }}
      run: |
        docker run --privileged -v $(pwd):$(pwd) -w $(pwd) -v /sys/kernel/debug:/sys/kernel/debug:rw -v /lib/modules:/lib/modules:ro -v /usr/src:/usr/src:ro -e STATIC_LINKING=${STATIC_LINKING} -e STATIC_LIBC=${STATIC_LIBC} -e EMBED_LLVM=${EMBED_LLVM} -e EMBED_CLANG=${EMBED_CLANG} -e EMBED_BCC=${EMBED_BCC} -e EMBED_LIBELF=${EMBED_LIBELF} -e EMBED_LIBCLANG_ONLY=${EMBED_LIBCLANG_ONLY} -e EMBED_BINUTILS=${EMBED_BINUTILS} --entrypoint /bin/bash bpftrace-embedded-${{ matrix.env['DISTRO'] }} -c "[[ -f $(pwd)/build-embedded/src/bpftrace ]] && ! readelf --dynamic $(pwd)/build-embedded/src/bpftrace | grep NEEDED | grep -v 'libm\|libc\|ld-linux\|libpthread\|libdl'"
    - name: Strip artifacts
      env: ${{ matrix.env }}
      if: matrix.env['TYPE'] == 'Release'
      run: |
        docker run --privileged -v $(pwd):$(pwd) -w $(pwd) -v /sys/kernel/debug:/sys/kernel/debug:rw -v /lib/modules:/lib/modules:ro -v /usr/src:/usr/src:ro -e STATIC_LINKING=${STATIC_LINKING} -e STATIC_LIBC=${STATIC_LIBC} -e EMBED_LLVM=${EMBED_LLVM} -e EMBED_CLANG=${EMBED_CLANG} -e EMBED_BCC=${EMBED_BCC} -e EMBED_LIBELF=${EMBED_LIBELF} -e EMBED_LIBCLANG_ONLY=${EMBED_LIBCLANG_ONLY} -e EMBED_BINUTILS=${EMBED_BINUTILS} --entrypoint /bin/bash bpftrace-embedded-${{ matrix.env['DISTRO'] }} -c "strip --keep-symbol BEGIN_trigger $(pwd)/build-embedded/src/bpftrace"

    - uses: actions/upload-artifact@v1
      with:
        name: bpftrace-${{ matrix.env['TYPE'] }}-${{ matrix.env['NAME'] }}
        path: build-embedded/src/bpftrace
    - uses: actions/upload-artifact@v1
      with:
        name: bpftrace_test-${{ matrix.env['TYPE'] }}-${{ matrix.env['NAME'] }}
        path: build-embedded/tests/bpftrace_test

    - name: Package docker image and push to quay.io
      if: matrix.env['TYPE'] == 'Release'
      env:
        QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
      run: |
        [[ -z "${QUAY_TOKEN}" ]] && echo "QUAY_TOKEN not set" && exit 0
        # Forks can push using this approach if they create a bot user of orgname+bpftrace_buildbot
        quay_user="$(dirname ${{ github.repository }})+bpftrace_buildbot"
        echo "${QUAY_TOKEN}" | docker login -u="${quay_user}" --password-stdin quay.io
        refname=$(basename ${{ github.ref }})
        typename=$(echo ${{ matrix.env['NAME'] }} | sed 's/+/_/g')
        docker build -t quay.io/${{ github.repository }}:${{ github.sha }}-${typename} -f docker/Dockerfile.minimal .
        docker tag quay.io/${{ github.repository }}:${{ github.sha }}-${typename} quay.io/${{ github.repository }}:${refname}-${typename}
        docker push quay.io/${{ github.repository }}:${{ github.sha }}-${typename}
        docker push quay.io/${{ github.repository }}:${refname}-${typename}

        [[ "${{ matrix.env['NAME'] }}" != "vanilla_llvm+clang+glibc2.27" ]] && exit 0
        echo "Pushing default release image for ref ${refname}"
        docker tag quay.io/${{ github.repository }}:${{ github.sha }}-${typename} quay.io/${{ github.repository }}:${refname}
        docker push quay.io/${{ github.repository }}:${refname}

        [[ "${refname}" != "master" ]] && exit 0
        echo "This is a build on master, pushing :latest tag also"
        docker tag quay.io/${{ github.repository }}:${{ github.sha }}-${typename} quay.io/${{ github.repository }}:latest
        docker push quay.io/${{ github.repository }}:latest
